// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI_Api.Models;

[Keyless]
[Table("sales")]
public partial class Sale
{
    [Column("ProductID")]
    public int? ProductId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string SalesmanName { get; set; }

    public int? Quantity { get; set; }
}